sudo: false
language: ruby

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.1
  - 2.2.5
  - 2.1.10

env:
  - PYTHON=python
  - PYTHON=python3 LIBPYTHON=wrong_value
  - LIBPYTHON=/usr/lib/libpython3.2mu.so.1

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-all

before_install:
  - gem update --system
  - gem update bundler
